version: '3'
services:
  api:
    build: ./api
    environment:
      - APP_MODULE="app:api"
      - WORKERS_PER_CORE="1"
      - FLASK_ENV="production"
      - SCRIPT_NAME=/api
      - PORT="5000"
    expose:
      - "5000"
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    expose:
      - "3000"
      
  proxy:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      - CERTBOT_EMAIL=jakegut0108@gmail.com
    volumes:
      - ./proxy/conf.d:/etc/nginx/user.conf.d
      - letsencrypt:/etc/letsencrypt
      
  worker:
    build: ./api
    
volumes:
  letsencrypt:
  