version: '3'
services:
  api:
    build: ./api
    environment:
      - APP_MODULE="app:api"
      - WORKERS_PER_CORE="1"
      - FLASK_ENV="production"
      - SCRIPT_NAME=/api
      - PORT="5000"
      - FORWARDED_ALLOW_IPS=*
    expose:
      - "5000"
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    expose:
      - "3000"
      
  proxy:
    restart: unless-stopped
    image: linuxserver/swag
    ports:
      - 80:80
      - 443:443
    environment:
      - EMAIL=jakegut0108+letsencrypt@gmail.com
      - URL=jakerg.me
      - SUBDOMAINS=git
      - VALIDATION=http
      - TZ=America/Chicago
      - ONLY_SUBDOMAINS=true
      - PUID=1000
      - PGID=1000
    volumes:
      - ./proxy/config:/config/nginx/site-confs
      - letsencrypt:/config/etc
      
  worker:
    build: ./api 

volumes:
  letsencrypt: