"""empty message

Revision ID: 18f4e883f1d4
Revises: baabeff2ec01
Create Date: 2020-07-23 17:03:34.208702

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '18f4e883f1d4'
down_revision = 'baabeff2ec01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gitdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.Text(), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('contributor_user', sa.Text(), nullable=True),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gitdata')
    # ### end Alembic commands ###
