"""Add token to User

Revision ID: 22bfe6f79d31
Revises: 00c6f59cf0af
Create Date: 2020-07-06 19:47:09.983046

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '22bfe6f79d31'
down_revision = '00c6f59cf0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_token')
    # ### end Alembic commands ###
