"""empty message

Revision ID: 4f1ebd450547
Revises: 6c166ab40586
Create Date: 2020-07-17 16:43:12.243801

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4f1ebd450547'
down_revision = '6c166ab40586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    project_types = postgresql.ENUM('individual', 'group_ind', 'group_group', name='projecttypes')
    project_types.create(op.get_bind())

    op.add_column('projects', sa.Column('due_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('projects', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('projects', sa.Column('type', project_types, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'type')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'due_date')

    op.execute("DROP TYPE projecttypes;")
    # ### end Alembic commands ###
