"""empty message

Revision ID: 6c166ab40586
Revises: 9933a5072c90
Create Date: 2020-07-14 15:56:54.180696

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6c166ab40586'
down_revision = '9933a5072c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.drop_constraint('groups_user_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'user_id')
    op.drop_column('groups', 'repo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('repo_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('groups_user_id_fkey', 'groups', 'users', ['user_id'], ['id'])
    op.drop_table('repos')
    # ### end Alembic commands ###
