"""empty message

Revision ID: 87697b31ecb8
Revises: 10d102686be3
Create Date: 2020-07-26 16:27:07.871689

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '87697b31ecb8'
down_revision = '10d102686be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'gitdata', ['sha'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gitdata', type_='unique')
    # ### end Alembic commands ###
