"""empty message

Revision ID: 9a25f78d4c9c
Revises: 4f1ebd450547
Create Date: 2020-07-17 18:57:08.849594

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9a25f78d4c9c'
down_revision = '4f1ebd450547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
