"""empty message

Revision ID: baabeff2ec01
Revises: 353c8ed27896
Create Date: 2020-07-22 17:12:21.798788

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'baabeff2ec01'
down_revision = '353c8ed27896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('webhook_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'webhook_id')
    # ### end Alembic commands ###
