"""empty message

Revision ID: c85e3350fbfd
Revises: da1b99185e0d
Create Date: 2020-07-31 16:36:15.266227

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c85e3350fbfd'
down_revision = 'da1b99185e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
