"""empty message

Revision ID: d007c513cddc
Revises: 22bfe6f79d31
Create Date: 2020-07-08 13:17:56.280997

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd007c513cddc'
down_revision = '22bfe6f79d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invites', ['username', 'course_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='unique')
    # ### end Alembic commands ###
